Repository EdenComp/GLaDOS, pull requests merged in 2024-01, with the labels that each got.

#83 Parsing: handling of comments
  src/Dreamberd/Parser.hs
Labels: enhancement, minor

#82 refacto parsing unit test
  src/Dreamberd/Parser.hs
  test/Unit/Dreamberd/TestDreamberdParsing.hs
Labels: chore

#85 Parsing: Implementation of float values
  src/Dreamberd/Bytecode/Decode.hs
  src/Dreamberd/Bytecode/Encode.hs
  src/Dreamberd/Compile.hs
  src/Dreamberd/Lib.hs
  src/Dreamberd/Parser.hs
  src/Dreamberd/Types.hs
  src/Dreamberd/Vm.hs
  test/Unit/Dreamberd/TestDreamberdBytecode.hs
  test/Unit/Dreamberd/TestDreamberdTypes.hs
  test/Unit/Dreamberd/TestDreamberdVm.hs
Labels: enhancement, minor

#88 Parsing: syntactic sugar for scopes with only one statement
  src/Dreamberd/Parser.hs
Labels: enhancement, minor

#91 feat: input function to read stdin
  src/Dreamberd/Vm.hs
Labels: enhancement

#92 feat: Now taking argument as variables (making them mutable)
  src/Dreamberd/Compilation/Compile.hs
Labels: enhancement, minor

#93 Compilation: generalization of the unary operators + and - to all expression
  src/Dreamberd/Compilation/Compile.hs
Labels: enhancement, minor

#95 Parsing: Returning without returning
  src/Dreamberd/Parser.hs
Labels: enhancement, minor

#99 feat(parser): now handle \ " \t \n \r \v \f \a \b \e \0
  src/Dreamberd/Parser.hs
Labels: enhancement

#109 feat: operators between integers and floats
  src/Dreamberd/Vm.hs
Labels: enhancement, minor

#110 feat: Preprocessing (2) - Optimizations
  src/Dreamberd/Compilation/Preprocessing.hs
Labels: enhancement, minor

#112 feat: unit tests on new vm operators
  src/Dreamberd/Vm.hs
  test/Unit/Dreamberd/TestDreamberdTypes.hs
  test/Unit/Dreamberd/TestDreamberdVm.hs
Labels: enhancement, minor

#113 Project documentation
  README.md
  docs/README.md
  docs/_assets/compilation-flow.png
  docs/_sidebar.md
  docs/general/compilation.md
Labels: documentation, minor

#115 fix: unit tests on builtin operations
  test/Unit/Dreamberd/TestDreamberdVm.hs
Labels: enhancement

#117 BNF updated with latest code changes
  docs/general/syntax.md
  dreamberd.bnf
Labels: documentation, enhancement, minor

#119 😢Lambdas with one parameters
  docs/general/syntax.md
  dreamberd.bnf
  src/Dreamberd/Parser.hs
  test/functional/src/dreamberd/test_lambda_basic.db4
  test/functional/src/dreamberd/test_lambda_inline.db4
  test/functional/src/dreamberd/test_lambda_simple_one_arg.db4
  test/functional/src/dreamberd/test_lambda_simple_one_arg.out
Labels: enhancement, patch
